---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: ap-south-1
    #your ip address
    allowed_ip: 183.82.226.224/32
  tasks:  
    - name: create security group  
      ec2_group:
        region: "{{ region }}"
        name: sg_webserver   
        description: security group for apsydney webserver host
        rules:
          # allow ssh access from your ip address  
          - proto: tcp  
            from_port: 22  
            to_port: 22  
            cidr_ip: "{{ allowed_ip }}"  
          # allow http access from anywhere  
          - proto: tcp  
            from_port: 80    
            to_port: 80    
            cidr_ip: 0.0.0.0/0  
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
